<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>MasterPilot.CustomData.Core</PackageId>
    <Version>0.1.1</Version>
    <Description>MasterPilot CustomData - pure C# transport layer</Description>
    <RootNamespace>MasterPilot.Communicator.CustomData</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
	<InternalsVisibleTo Include="CustomData.Tests" />
  </ItemGroup>

</Project>
