syntax = "proto3";

package masterpilot.proto;

option csharp_namespace = "MasterPilot.Communicator.ProtoMessages";

// 线性数据表示
message SignedLinearValue {
  sint32 value = 1; // 当前数据值大小, 有符号
  uint32 boundary = 2; // 数据范围, 表示value会被归一化到 [-boundary, +boundary], 闭区间
}

message UnsignedLinearValue {
  uint32 value = 1; // 当前数据值大小, 无符号
  uint32 max = 2; // 数据范围, 表示value会被归一化到 [0, max], 闭区间
}

// 视觉目标类型 (对应 VisionTargetType)
enum VisionTarget {
  VT_NONE = 0;
  VT_NORMAL = 1;
  VT_SMALL_RUNE = 2;
  VT_LARGE_RUNE = 3;
  VT_OUTPOST = 4;
  VT_BASE = 5;
  VT_HERO = 6;
}

// 视觉自瞄状态 (对应 VisionStateType)
enum VisionState {
  VS_INACTIVE = 0; // 未激活
  VS_ACTIVE = 1; // 激活
  VS_TARGET_FOUND = 2; // 已找到目标
}

// 视觉状态
message VisionData {
  VisionTarget target = 1; // 视觉识别目标类型
  VisionState state = 2; // 视觉/自瞄状态
}

// 武器/发射机构状态 (对应 WeaponStatus)
message WeaponState {
  bool fric_on = 1;
  bool fric_online = 2;
  float pitch = 4; // 枪管相对地面 degree
  float yaw = 5;   // 枪管相对前方 degree
}

enum ChassisMode {
  CM_NORMAL = 0; // 正常状态
  CM_GYRO = 1;    // 陀螺
  CM_STEPUP = 2; // 上台阶
  CM_STEPDOWN = 3; // 下台阶
  CM_LAUNCH = 4;    // 飞坡
  CM_JUMP = 5;   // 跳跃
}

// 底盘状态 
message ChassisState {
  float speed = 1;      // 线速度 m/s
  float yaw = 3; // 速度相对底盘前方 degree
  float pitch = 4;      // 底盘相对地面pitch degree.
  float roll = 5;       // 底盘相对地面roll degree.
  ChassisMode mode = 6; // 底盘模式
  float cap_ratio = 7; // 超电百分比
  uint64 rfid = 8;	// RFID数据, 详见通信协议手册0x0209的说明
  float height = 11; // 离地高度. 单位: m
}

enum LegMode {
  LM_OFF = 0;
  LM_LOW = 1;
  LM_MID = 2;
  LM_HIGH = 3;
}

message LegInfo {
    // 二选一发送
    oneof state {
        LegMode mode = 1; // 腿模式枚举, 提供高中低三档
        UnsignedLinearValue height = 2; // 腿高线性数据
    };
    float small_theta = 10; // 小腿theta, degree
    float large_theta = 11; // 大腿theta, degree
}

enum BuffType {
  B_NONE = 0;
  B_RECOVERY = 1; // 恢复增益
  B_COOLING = 2; // 冷却增益
  B_DEFENSE = 3; // 防御增益
  B_VULNERABILITY = 4; // 易伤
  B_ATTACK = 5; // 攻击增益
}

message BuffInfo {
  BuffType type = 1;
  uint32 strength = 2; // 参考官方通信手册里说的值. 0x0204
}

message RobotInfoFromRadio {
  uint32 id = 1;     // 一位数机器人编号
  uint32 health = 2; // 血量
  uint32 ammo = 3;   // 剩余发弹量
  repeated BuffInfo buffs = 6;
}

// 雷达无线电解密
message RadioInfo {
  uint32 enemy_current_eco = 1;                 // 对方剩余经济
  uint32 enemy_total_eco = 2;                   // 对方总经济
  uint32 rfid = 3;                              // 对方一大堆RFID的状态 0x0a04
  repeated RobotInfoFromRadio enemy_robots = 4; // 对方机器人信息
}

// 图传相关参数
// 图传外参参考来源
enum VTRelative
{
	VTR_NONE = 0; // 无效
	VTR_WEAPON = 1; // 枪管
	VTR_CHASSIS = 2; // 底盘
	VTR_ARM = 3; // 机械臂
	VTR_WORLD = 10; // 场地(绝对坐标)
}
// 图传外参
message VTExtrinsic
{
	VTRelative relative = 67;
	float x = 1; // x偏移. x+ 表示在右边. 单位: m
	float y = 2; // y偏移. y+ 表示在上方. 单位: m
	float z = 3; // z偏移. z- 表示在前方. 单位: m
	float yaw = 11; // yaw弧度. 逆时针. 单位: rad
	float pitch = 12; // pitch弧度. 逆时针. 单位: rad
	float roll = 13; // roll弧度. 逆时针. 单位: rad
}