syntax = "proto3";

import "masterpilot/proto/common.proto";

package masterpilot.proto;
option csharp_namespace = "MasterPilot.Communicator.ProtoMessages";


enum DronePidMode {
  DPM_INACTIVE = 0;
  DPM_MEC = 1;
  DPM_GYRO = 2;
  DPM_VISION = 3;
}

enum DroneLampCmd {
  DLC_IDLE = 0;
  DLC_RC_OFFLINE = 1;
  DLC_AWAIT = 2;
  DLC_BASE = 3;
  DLC_OUTPOST = 4;
  DLC_BUF = 5;
  DLC_FORWARD = 6;
  DLC_BACK = 7;
  DLC_LEFT = 8;
  DLC_RIGHT = 9;
  DLC_CW_SPIN = 10;
  DLC_CCW_SPIN = 11;
  DLC_UP = 12;
  DLC_DOWN = 13;
}

message DroneDataPacketToClient {
  optional WeaponState weapon = 1;
  optional VisionData vision = 2;
  optional DroneLampCmd lamp = 3;
  optional DronePidMode pid = 4;
  optional RadioInfo radio_info = 8;
}
