syntax = "proto3";

import "masterpilot/proto/common.proto";

package masterpilot.proto;
option csharp_namespace = "MasterPilot.Communicator.ProtoMessages";

enum HeroCommandType
{
	HC_NONE = 0;
	HC_DEPLOY_ENTER = 1; // 进入部署模式
	HC_DEPLOY_EXIT = 2; // 退出部署模式
}

// 英雄发送给自定义客户端的数据
message HeroDataPacketToClient {
  optional WeaponState weapon = 1;
  optional ChassisState chassis = 2;
  optional VisionData vision = 3;
  optional LegInfo leg_state = 5;
  optional RadioInfo radio_info = 8;
  repeated HeroCommandType commands = 11;
  // 压缩后的相机画面
  optional bytes camera_frame = 200;
}
