syntax = "proto3";

import "nanopb.proto";
import "masterpilot/proto/common.proto";

package masterpilot.proto;
option csharp_namespace = "MasterPilot.Communicator.ProtoMessages";
option (nanopb_fileopt).package = "MP";
option (nanopb_fileopt).long_names = false;

message InfantryDataPacketToClient {
  optional WeaponState weapon = 1;
  optional ChassisState chassis = 2;
  optional VisionData vision = 3;
  optional PowerState power = 4;
  optional LegMode leg_mode = 5;

  optional RadioInfo radio_info = 8;
}
