syntax = "proto3";

option csharp_namespace = "MasterPilot.Communicator.ProtoMessages.Common";

// 视觉目标类型 (对应 VisionTargetType)
enum VisionTarget {
  VT_NONE = 0;
  VT_NORMAL = 1;
  VT_SMALL_RUNE = 2;
  VT_LARGE_RUNE = 3;
  VT_OUTPOST = 4;
  VT_BASE = 5;
  VT_HERO = 6;
}

// 视觉自瞄状态 (对应 VisionStateType)
enum VisionState {
  VS_INACTIVE = 0;
  VS_ACTIVE = 1;
  VS_TARGET_FOUND = 2;
}

// 视觉状态
message VisionData {
  VisionTarget target = 1;
  VisionState state = 2;
}

// 武器/发射机构状态 (对应 WeaponStatus)
message WeaponState {
  bool fric_on = 1;
  bool fric_online = 2;
  float pitch = 4; // degree
  float yaw = 5;   // degree
}

message ChassisModeFlags {
  bool top_flag = 1;    // 陀螺模式
  bool upstep_flag = 2; // 上台阶模式
  bool fly_flag = 3;    // 飞坡模式
  bool jump_flag = 4;   // 跳跃模式
}

// 底盘实时状态 (对应 ChassisStatus 部分字段)
message ChassisState {
  float speed = 1;      // m/s
  float theta = 2;      // 摆角 degree
  float yaw_offset = 3; // degree
  float pitch = 4;      // degree
  float roll = 5;       // degree
  ChassisModeFlags mode_flags = 6;
}

// 能源与电容状态
message PowerState {
  float cap_voltage_ratio = 1; // 电容电压比
}

enum LegMode {
  LM_LOW = 0;
  LM_MID = 1;
  LM_HIGH = 2;
}

enum BuffType {
  B_NONE = 0;
  B_RECOVERY = 1;
  B_COOLING = 2;
  B_DEFENSE = 3;
  B_VULNERABILITY = 4;
  B_ATTACK = 5;
}

message BuffInfo {
  BuffType type = 1;
  uint32 strength = 2; // 参考官方通信手册里说的值. 0x0204
}

message RobotInfoFromRadio {
  uint32 id = 1;     // 一位数机器人编号
  uint32 health = 2; // 血量
  uint32 ammo = 3;   // 剩余发弹量
  repeated BuffInfo buffs = 6;
}

// 雷达无线电解密
message RadioInfo {
  uint32 enemy_current_eco = 1;                 // 对方剩余经济
  uint32 enemy_total_eco = 2;                   // 对方总经济
  uint32 rfid = 3;                              // 对方一大堆RFID的状态 0x0a04
  repeated RobotInfoFromRadio enemy_robots = 4; // 对方机器人信息
}