/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MASTERPILOT_PROTO_TEST_TEST_PB_H_INCLUDED
#define PB_MASTERPILOT_PROTO_TEST_TEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(200) TestMessage_data_t;
typedef PB_BYTES_ARRAY_T(200) TestMessage_extra_t;
/* 测试用消息 */
typedef struct _TestMessage {
    uint32_t id; /* 测试用id */
    TestMessage_data_t data; /* 测试截断用的大data */
    TestMessage_extra_t extra; /* 测试跨字段截断用的大byte */
} TestMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define TestMessage_init_default                 {0, {0, {0}}, {0, {0}}}
#define TestMessage_init_zero                    {0, {0, {0}}, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define TestMessage_id_tag                       1
#define TestMessage_data_tag                     2
#define TestMessage_extra_tag                    3

/* Struct field encoding specification for nanopb */
#define TestMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, BYTES,    data,              2) \
X(a, STATIC,   SINGULAR, BYTES,    extra,             3)
#define TestMessage_CALLBACK NULL
#define TestMessage_DEFAULT NULL

extern const pb_msgdesc_t TestMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TestMessage_fields &TestMessage_msg

/* Maximum encoded size of messages (where known) */
#define MASTERPILOT_PROTO_TEST_TEST_PB_H_MAX_SIZE TestMessage_size
#define TestMessage_size                         412

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
