/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "masterpilot/proto/common.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MP_SignedLinearValue, MP_SignedLinearValue, AUTO)


PB_BIND(MP_UnsignedLinearValue, MP_UnsignedLinearValue, AUTO)


PB_BIND(MP_VisionData, MP_VisionData, AUTO)


PB_BIND(MP_WeaponState, MP_WeaponState, AUTO)


PB_BIND(MP_ChassisState, MP_ChassisState, AUTO)


PB_BIND(MP_LegInfo, MP_LegInfo, AUTO)


PB_BIND(MP_BuffInfo, MP_BuffInfo, AUTO)


PB_BIND(MP_RobotInfoFromRadio, MP_RobotInfoFromRadio, AUTO)


PB_BIND(MP_RadioInfo, MP_RadioInfo, 2)


PB_BIND(MP_VTExtrinsic, MP_VTExtrinsic, 2)















