/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "masterpilot/proto/engineer.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MP_ArmState, MP_ArmState, AUTO)


PB_BIND(MP_RobotStatus, MP_RobotStatus, AUTO)


PB_BIND(MP_EngineerDataPacketToClient, MP_EngineerDataPacketToClient, 2)







