/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MASTERPILOT_PROTO_MASTERPILOT_PROTO_COMMON_PB_H_INCLUDED
#define PB_MASTERPILOT_PROTO_MASTERPILOT_PROTO_COMMON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 视觉目标类型 (对应 VisionTargetType) */
typedef enum _MP_VisionTarget {
    MP_VT_NONE = 0,
    MP_VT_NORMAL = 1,
    MP_VT_SMALL_RUNE = 2,
    MP_VT_LARGE_RUNE = 3,
    MP_VT_OUTPOST = 4,
    MP_VT_BASE = 5,
    MP_VT_HERO = 6
} MP_VisionTarget;

/* 视觉自瞄状态 (对应 VisionStateType) */
typedef enum _MP_VisionState {
    MP_VS_INACTIVE = 0, /* 未激活 */
    MP_VS_ACTIVE = 1, /* 激活 */
    MP_VS_TARGET_FOUND = 2 /* 已找到目标 */
} MP_VisionState;

typedef enum _MP_ChassisMode {
    MP_CM_NORMAL = 0, /* 正常状态 */
    MP_CM_GYRO = 1, /* 陀螺 */
    MP_CM_STEPUP = 2, /* 上台阶 */
    MP_CM_STEPDOWN = 3, /* 下台阶 */
    MP_CM_LAUNCH = 4, /* 飞坡 */
    MP_CM_JUMP = 5 /* 跳跃 */
} MP_ChassisMode;

typedef enum _MP_LegMode {
    MP_LM_OFF = 0,
    MP_LM_LOW = 1,
    MP_LM_MID = 2,
    MP_LM_HIGH = 3
} MP_LegMode;

typedef enum _MP_BuffType {
    MP_B_NONE = 0,
    MP_B_RECOVERY = 1, /* 恢复增益 */
    MP_B_COOLING = 2, /* 冷却增益 */
    MP_B_DEFENSE = 3, /* 防御增益 */
    MP_B_VULNERABILITY = 4, /* 易伤 */
    MP_B_ATTACK = 5 /* 攻击增益 */
} MP_BuffType;

/* 图传相关参数
 图传外参参考来源 */
typedef enum _MP_VTRelative {
    MP_VTR_NONE = 0, /* 无效 */
    MP_VTR_WEAPON = 1, /* 枪管 */
    MP_VTR_CHASSIS = 2, /* 底盘 */
    MP_VTR_ARM = 3, /* 机械臂 */
    MP_VTR_WORLD = 10 /* 场地(绝对坐标) */
} MP_VTRelative;

/* Struct definitions */
/* 线性数据表示 */
typedef struct _MP_SignedLinearValue {
    int32_t value; /* 当前数据值大小, 有符号 */
    uint32_t boundary; /* 数据范围, 表示value会被归一化到 [-boundary, +boundary], 闭区间 */
} MP_SignedLinearValue;

typedef struct _MP_UnsignedLinearValue {
    uint32_t value; /* 当前数据值大小, 无符号 */
    uint32_t max; /* 数据范围, 表示value会被归一化到 [0, max], 闭区间 */
} MP_UnsignedLinearValue;

/* 视觉状态 */
typedef struct _MP_VisionData {
    MP_VisionTarget target; /* 视觉识别目标类型 */
    MP_VisionState state; /* 视觉/自瞄状态 */
} MP_VisionData;

/* 武器/发射机构状态 (对应 WeaponStatus) */
typedef struct _MP_WeaponState {
    bool fric_on;
    bool fric_online;
    float pitch; /* 枪管相对地面 degree */
    float yaw; /* 枪管相对前方 degree */
} MP_WeaponState;

/* 底盘状态 */
typedef struct _MP_ChassisState {
    float speed; /* 线速度 m/s */
    float yaw; /* 速度相对底盘前方 degree */
    float pitch; /* 底盘相对地面pitch degree. */
    float roll; /* 底盘相对地面roll degree. */
    MP_ChassisMode mode; /* 底盘模式 */
    float cap_ratio; /* 超电百分比 */
    uint32_t rfid; /* RFID数据, 详见通信协议手册0x0209的说明 */
    float height; /* 离地高度. 单位: m */
} MP_ChassisState;

typedef struct _MP_LegInfo {
    pb_size_t which_state;
    union {
        MP_LegMode mode; /* 腿模式枚举, 提供高中低三档 */
        MP_UnsignedLinearValue height; /* 腿高线性数据 */
    } state;
    float small_theta; /* 小腿theta, degree */
    float large_theta; /* 大腿theta, degree */
} MP_LegInfo;

typedef struct _MP_BuffInfo {
    MP_BuffType type;
    uint32_t strength; /* 参考官方通信手册里说的值. 0x0204 */
} MP_BuffInfo;

typedef struct _MP_RobotInfoFromRadio {
    uint32_t id; /* 一位数机器人编号 */
    uint32_t health; /* 血量 */
    uint32_t ammo; /* 剩余发弹量 */
    pb_size_t buffs_count;
    MP_BuffInfo buffs[6];
} MP_RobotInfoFromRadio;

/* 雷达无线电解密 */
typedef struct _MP_RadioInfo {
    uint32_t enemy_current_eco; /* 对方剩余经济 */
    uint32_t enemy_total_eco; /* 对方总经济 */
    uint32_t rfid; /* 对方一大堆RFID的状态 0x0a04 */
    pb_size_t enemy_robots_count;
    MP_RobotInfoFromRadio enemy_robots[6]; /* 对方机器人信息 */
} MP_RadioInfo;

/* 图传外参 */
typedef struct _MP_VTExtrinsic {
    float x; /* x偏移. x+ 表示在右边. 单位: m */
    float y; /* y偏移. y+ 表示在上方. 单位: m */
    float z; /* z偏移. z- 表示在前方. 单位: m */
    float yaw; /* yaw弧度. 逆时针. 单位: rad */
    float pitch; /* pitch弧度. 逆时针. 单位: rad */
    float roll; /* roll弧度. 逆时针. 单位: rad */
    MP_VTRelative relative;
} MP_VTExtrinsic;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _MP_VisionTarget_MIN MP_VT_NONE
#define _MP_VisionTarget_MAX MP_VT_HERO
#define _MP_VisionTarget_ARRAYSIZE ((MP_VisionTarget)(MP_VT_HERO+1))
#define MP_VisionTarget_VT_NONE MP_VT_NONE
#define MP_VisionTarget_VT_NORMAL MP_VT_NORMAL
#define MP_VisionTarget_VT_SMALL_RUNE MP_VT_SMALL_RUNE
#define MP_VisionTarget_VT_LARGE_RUNE MP_VT_LARGE_RUNE
#define MP_VisionTarget_VT_OUTPOST MP_VT_OUTPOST
#define MP_VisionTarget_VT_BASE MP_VT_BASE
#define MP_VisionTarget_VT_HERO MP_VT_HERO

#define _MP_VisionState_MIN MP_VS_INACTIVE
#define _MP_VisionState_MAX MP_VS_TARGET_FOUND
#define _MP_VisionState_ARRAYSIZE ((MP_VisionState)(MP_VS_TARGET_FOUND+1))
#define MP_VisionState_VS_INACTIVE MP_VS_INACTIVE
#define MP_VisionState_VS_ACTIVE MP_VS_ACTIVE
#define MP_VisionState_VS_TARGET_FOUND MP_VS_TARGET_FOUND

#define _MP_ChassisMode_MIN MP_CM_NORMAL
#define _MP_ChassisMode_MAX MP_CM_JUMP
#define _MP_ChassisMode_ARRAYSIZE ((MP_ChassisMode)(MP_CM_JUMP+1))
#define MP_ChassisMode_CM_NORMAL MP_CM_NORMAL
#define MP_ChassisMode_CM_GYRO MP_CM_GYRO
#define MP_ChassisMode_CM_STEPUP MP_CM_STEPUP
#define MP_ChassisMode_CM_STEPDOWN MP_CM_STEPDOWN
#define MP_ChassisMode_CM_LAUNCH MP_CM_LAUNCH
#define MP_ChassisMode_CM_JUMP MP_CM_JUMP

#define _MP_LegMode_MIN MP_LM_OFF
#define _MP_LegMode_MAX MP_LM_HIGH
#define _MP_LegMode_ARRAYSIZE ((MP_LegMode)(MP_LM_HIGH+1))
#define MP_LegMode_LM_OFF MP_LM_OFF
#define MP_LegMode_LM_LOW MP_LM_LOW
#define MP_LegMode_LM_MID MP_LM_MID
#define MP_LegMode_LM_HIGH MP_LM_HIGH

#define _MP_BuffType_MIN MP_B_NONE
#define _MP_BuffType_MAX MP_B_ATTACK
#define _MP_BuffType_ARRAYSIZE ((MP_BuffType)(MP_B_ATTACK+1))
#define MP_BuffType_B_NONE MP_B_NONE
#define MP_BuffType_B_RECOVERY MP_B_RECOVERY
#define MP_BuffType_B_COOLING MP_B_COOLING
#define MP_BuffType_B_DEFENSE MP_B_DEFENSE
#define MP_BuffType_B_VULNERABILITY MP_B_VULNERABILITY
#define MP_BuffType_B_ATTACK MP_B_ATTACK

#define _MP_VTRelative_MIN MP_VTR_NONE
#define _MP_VTRelative_MAX MP_VTR_WORLD
#define _MP_VTRelative_ARRAYSIZE ((MP_VTRelative)(MP_VTR_WORLD+1))
#define MP_VTRelative_VTR_NONE MP_VTR_NONE
#define MP_VTRelative_VTR_WEAPON MP_VTR_WEAPON
#define MP_VTRelative_VTR_CHASSIS MP_VTR_CHASSIS
#define MP_VTRelative_VTR_ARM MP_VTR_ARM
#define MP_VTRelative_VTR_WORLD MP_VTR_WORLD



#define MP_VisionData_target_ENUMTYPE MP_VisionTarget
#define MP_VisionData_state_ENUMTYPE MP_VisionState


#define MP_ChassisState_mode_ENUMTYPE MP_ChassisMode

#define MP_LegInfo_state_mode_ENUMTYPE MP_LegMode

#define MP_BuffInfo_type_ENUMTYPE MP_BuffType



#define MP_VTExtrinsic_relative_ENUMTYPE MP_VTRelative


/* Initializer values for message structs */
#define MP_SignedLinearValue_init_default        {0, 0}
#define MP_UnsignedLinearValue_init_default      {0, 0}
#define MP_VisionData_init_default               {_MP_VisionTarget_MIN, _MP_VisionState_MIN}
#define MP_WeaponState_init_default              {0, 0, 0, 0}
#define MP_ChassisState_init_default             {0, 0, 0, 0, _MP_ChassisMode_MIN, 0, 0, 0}
#define MP_LegInfo_init_default                  {0, {_MP_LegMode_MIN}, 0, 0}
#define MP_BuffInfo_init_default                 {_MP_BuffType_MIN, 0}
#define MP_RobotInfoFromRadio_init_default       {0, 0, 0, 0, {MP_BuffInfo_init_default, MP_BuffInfo_init_default, MP_BuffInfo_init_default, MP_BuffInfo_init_default, MP_BuffInfo_init_default, MP_BuffInfo_init_default}}
#define MP_RadioInfo_init_default                {0, 0, 0, 0, {MP_RobotInfoFromRadio_init_default, MP_RobotInfoFromRadio_init_default, MP_RobotInfoFromRadio_init_default, MP_RobotInfoFromRadio_init_default, MP_RobotInfoFromRadio_init_default, MP_RobotInfoFromRadio_init_default}}
#define MP_VTExtrinsic_init_default              {0, 0, 0, 0, 0, 0, _MP_VTRelative_MIN}
#define MP_SignedLinearValue_init_zero           {0, 0}
#define MP_UnsignedLinearValue_init_zero         {0, 0}
#define MP_VisionData_init_zero                  {_MP_VisionTarget_MIN, _MP_VisionState_MIN}
#define MP_WeaponState_init_zero                 {0, 0, 0, 0}
#define MP_ChassisState_init_zero                {0, 0, 0, 0, _MP_ChassisMode_MIN, 0, 0, 0}
#define MP_LegInfo_init_zero                     {0, {_MP_LegMode_MIN}, 0, 0}
#define MP_BuffInfo_init_zero                    {_MP_BuffType_MIN, 0}
#define MP_RobotInfoFromRadio_init_zero          {0, 0, 0, 0, {MP_BuffInfo_init_zero, MP_BuffInfo_init_zero, MP_BuffInfo_init_zero, MP_BuffInfo_init_zero, MP_BuffInfo_init_zero, MP_BuffInfo_init_zero}}
#define MP_RadioInfo_init_zero                   {0, 0, 0, 0, {MP_RobotInfoFromRadio_init_zero, MP_RobotInfoFromRadio_init_zero, MP_RobotInfoFromRadio_init_zero, MP_RobotInfoFromRadio_init_zero, MP_RobotInfoFromRadio_init_zero, MP_RobotInfoFromRadio_init_zero}}
#define MP_VTExtrinsic_init_zero                 {0, 0, 0, 0, 0, 0, _MP_VTRelative_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define MP_SignedLinearValue_value_tag           1
#define MP_SignedLinearValue_boundary_tag        2
#define MP_UnsignedLinearValue_value_tag         1
#define MP_UnsignedLinearValue_max_tag           2
#define MP_VisionData_target_tag                 1
#define MP_VisionData_state_tag                  2
#define MP_WeaponState_fric_on_tag               1
#define MP_WeaponState_fric_online_tag           2
#define MP_WeaponState_pitch_tag                 4
#define MP_WeaponState_yaw_tag                   5
#define MP_ChassisState_speed_tag                1
#define MP_ChassisState_yaw_tag                  3
#define MP_ChassisState_pitch_tag                4
#define MP_ChassisState_roll_tag                 5
#define MP_ChassisState_mode_tag                 6
#define MP_ChassisState_cap_ratio_tag            7
#define MP_ChassisState_rfid_tag                 8
#define MP_ChassisState_height_tag               11
#define MP_LegInfo_mode_tag                      1
#define MP_LegInfo_height_tag                    2
#define MP_LegInfo_small_theta_tag               10
#define MP_LegInfo_large_theta_tag               11
#define MP_BuffInfo_type_tag                     1
#define MP_BuffInfo_strength_tag                 2
#define MP_RobotInfoFromRadio_id_tag             1
#define MP_RobotInfoFromRadio_health_tag         2
#define MP_RobotInfoFromRadio_ammo_tag           3
#define MP_RobotInfoFromRadio_buffs_tag          6
#define MP_RadioInfo_enemy_current_eco_tag       1
#define MP_RadioInfo_enemy_total_eco_tag         2
#define MP_RadioInfo_rfid_tag                    3
#define MP_RadioInfo_enemy_robots_tag            4
#define MP_VTExtrinsic_x_tag                     1
#define MP_VTExtrinsic_y_tag                     2
#define MP_VTExtrinsic_z_tag                     3
#define MP_VTExtrinsic_yaw_tag                   11
#define MP_VTExtrinsic_pitch_tag                 12
#define MP_VTExtrinsic_roll_tag                  13
#define MP_VTExtrinsic_relative_tag              67

/* Struct field encoding specification for nanopb */
#define MP_SignedLinearValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   value,             1) \
X(a, STATIC,   SINGULAR, UINT32,   boundary,          2)
#define MP_SignedLinearValue_CALLBACK NULL
#define MP_SignedLinearValue_DEFAULT NULL

#define MP_UnsignedLinearValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   value,             1) \
X(a, STATIC,   SINGULAR, UINT32,   max,               2)
#define MP_UnsignedLinearValue_CALLBACK NULL
#define MP_UnsignedLinearValue_DEFAULT NULL

#define MP_VisionData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    target,            1) \
X(a, STATIC,   SINGULAR, UENUM,    state,             2)
#define MP_VisionData_CALLBACK NULL
#define MP_VisionData_DEFAULT NULL

#define MP_WeaponState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     fric_on,           1) \
X(a, STATIC,   SINGULAR, BOOL,     fric_online,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    pitch,             4) \
X(a, STATIC,   SINGULAR, FLOAT,    yaw,               5)
#define MP_WeaponState_CALLBACK NULL
#define MP_WeaponState_DEFAULT NULL

#define MP_ChassisState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    yaw,               3) \
X(a, STATIC,   SINGULAR, FLOAT,    pitch,             4) \
X(a, STATIC,   SINGULAR, FLOAT,    roll,              5) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              6) \
X(a, STATIC,   SINGULAR, FLOAT,    cap_ratio,         7) \
X(a, STATIC,   SINGULAR, UINT32,   rfid,              8) \
X(a, STATIC,   SINGULAR, FLOAT,    height,           11)
#define MP_ChassisState_CALLBACK NULL
#define MP_ChassisState_DEFAULT NULL

#define MP_LegInfo_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UENUM,    (state,mode,state.mode),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (state,height,state.height),   2) \
X(a, STATIC,   SINGULAR, FLOAT,    small_theta,      10) \
X(a, STATIC,   SINGULAR, FLOAT,    large_theta,      11)
#define MP_LegInfo_CALLBACK NULL
#define MP_LegInfo_DEFAULT NULL
#define MP_LegInfo_state_height_MSGTYPE MP_UnsignedLinearValue

#define MP_BuffInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, UINT32,   strength,          2)
#define MP_BuffInfo_CALLBACK NULL
#define MP_BuffInfo_DEFAULT NULL

#define MP_RobotInfoFromRadio_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, UINT32,   health,            2) \
X(a, STATIC,   SINGULAR, UINT32,   ammo,              3) \
X(a, STATIC,   REPEATED, MESSAGE,  buffs,             6)
#define MP_RobotInfoFromRadio_CALLBACK NULL
#define MP_RobotInfoFromRadio_DEFAULT NULL
#define MP_RobotInfoFromRadio_buffs_MSGTYPE MP_BuffInfo

#define MP_RadioInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   enemy_current_eco,   1) \
X(a, STATIC,   SINGULAR, UINT32,   enemy_total_eco,   2) \
X(a, STATIC,   SINGULAR, UINT32,   rfid,              3) \
X(a, STATIC,   REPEATED, MESSAGE,  enemy_robots,      4)
#define MP_RadioInfo_CALLBACK NULL
#define MP_RadioInfo_DEFAULT NULL
#define MP_RadioInfo_enemy_robots_MSGTYPE MP_RobotInfoFromRadio

#define MP_VTExtrinsic_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3) \
X(a, STATIC,   SINGULAR, FLOAT,    yaw,              11) \
X(a, STATIC,   SINGULAR, FLOAT,    pitch,            12) \
X(a, STATIC,   SINGULAR, FLOAT,    roll,             13) \
X(a, STATIC,   SINGULAR, UENUM,    relative,         67)
#define MP_VTExtrinsic_CALLBACK NULL
#define MP_VTExtrinsic_DEFAULT NULL

extern const pb_msgdesc_t MP_SignedLinearValue_msg;
extern const pb_msgdesc_t MP_UnsignedLinearValue_msg;
extern const pb_msgdesc_t MP_VisionData_msg;
extern const pb_msgdesc_t MP_WeaponState_msg;
extern const pb_msgdesc_t MP_ChassisState_msg;
extern const pb_msgdesc_t MP_LegInfo_msg;
extern const pb_msgdesc_t MP_BuffInfo_msg;
extern const pb_msgdesc_t MP_RobotInfoFromRadio_msg;
extern const pb_msgdesc_t MP_RadioInfo_msg;
extern const pb_msgdesc_t MP_VTExtrinsic_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MP_SignedLinearValue_fields &MP_SignedLinearValue_msg
#define MP_UnsignedLinearValue_fields &MP_UnsignedLinearValue_msg
#define MP_VisionData_fields &MP_VisionData_msg
#define MP_WeaponState_fields &MP_WeaponState_msg
#define MP_ChassisState_fields &MP_ChassisState_msg
#define MP_LegInfo_fields &MP_LegInfo_msg
#define MP_BuffInfo_fields &MP_BuffInfo_msg
#define MP_RobotInfoFromRadio_fields &MP_RobotInfoFromRadio_msg
#define MP_RadioInfo_fields &MP_RadioInfo_msg
#define MP_VTExtrinsic_fields &MP_VTExtrinsic_msg

/* Maximum encoded size of messages (where known) */
#define MASTERPILOT_PROTO_MASTERPILOT_PROTO_COMMON_PB_H_MAX_SIZE MP_RadioInfo_size
#define MP_BuffInfo_size                         8
#define MP_ChassisState_size                     38
#define MP_LegInfo_size                          24
#define MP_RadioInfo_size                        498
#define MP_RobotInfoFromRadio_size               78
#define MP_SignedLinearValue_size                12
#define MP_UnsignedLinearValue_size              12
#define MP_VTExtrinsic_size                      33
#define MP_VisionData_size                       4
#define MP_WeaponState_size                      14

/* Mapping from canonical names (mangle_names or overridden package name) */
#define masterpilot_proto_VisionTarget MP_VisionTarget
#define masterpilot_proto_VisionState MP_VisionState
#define masterpilot_proto_ChassisMode MP_ChassisMode
#define masterpilot_proto_LegMode MP_LegMode
#define masterpilot_proto_BuffType MP_BuffType
#define masterpilot_proto_VTRelative MP_VTRelative
#define masterpilot_proto_SignedLinearValue MP_SignedLinearValue
#define masterpilot_proto_UnsignedLinearValue MP_UnsignedLinearValue
#define masterpilot_proto_VisionData MP_VisionData
#define masterpilot_proto_WeaponState MP_WeaponState
#define masterpilot_proto_ChassisState MP_ChassisState
#define masterpilot_proto_LegInfo MP_LegInfo
#define masterpilot_proto_BuffInfo MP_BuffInfo
#define masterpilot_proto_RobotInfoFromRadio MP_RobotInfoFromRadio
#define masterpilot_proto_RadioInfo MP_RadioInfo
#define masterpilot_proto_VTExtrinsic MP_VTExtrinsic
#define _masterpilot_proto_VisionTarget_MIN _MP_VisionTarget_MIN
#define _masterpilot_proto_VisionTarget_MAX _MP_VisionTarget_MAX
#define _masterpilot_proto_VisionTarget_ARRAYSIZE _MP_VisionTarget_ARRAYSIZE
#define _masterpilot_proto_VisionState_MIN _MP_VisionState_MIN
#define _masterpilot_proto_VisionState_MAX _MP_VisionState_MAX
#define _masterpilot_proto_VisionState_ARRAYSIZE _MP_VisionState_ARRAYSIZE
#define _masterpilot_proto_ChassisMode_MIN _MP_ChassisMode_MIN
#define _masterpilot_proto_ChassisMode_MAX _MP_ChassisMode_MAX
#define _masterpilot_proto_ChassisMode_ARRAYSIZE _MP_ChassisMode_ARRAYSIZE
#define _masterpilot_proto_LegMode_MIN _MP_LegMode_MIN
#define _masterpilot_proto_LegMode_MAX _MP_LegMode_MAX
#define _masterpilot_proto_LegMode_ARRAYSIZE _MP_LegMode_ARRAYSIZE
#define _masterpilot_proto_BuffType_MIN _MP_BuffType_MIN
#define _masterpilot_proto_BuffType_MAX _MP_BuffType_MAX
#define _masterpilot_proto_BuffType_ARRAYSIZE _MP_BuffType_ARRAYSIZE
#define _masterpilot_proto_VTRelative_MIN _MP_VTRelative_MIN
#define _masterpilot_proto_VTRelative_MAX _MP_VTRelative_MAX
#define _masterpilot_proto_VTRelative_ARRAYSIZE _MP_VTRelative_ARRAYSIZE
#define masterpilot_proto_SignedLinearValue_init_default MP_SignedLinearValue_init_default
#define masterpilot_proto_UnsignedLinearValue_init_default MP_UnsignedLinearValue_init_default
#define masterpilot_proto_VisionData_init_default MP_VisionData_init_default
#define masterpilot_proto_WeaponState_init_default MP_WeaponState_init_default
#define masterpilot_proto_ChassisState_init_default MP_ChassisState_init_default
#define masterpilot_proto_LegInfo_init_default MP_LegInfo_init_default
#define masterpilot_proto_BuffInfo_init_default MP_BuffInfo_init_default
#define masterpilot_proto_RobotInfoFromRadio_init_default MP_RobotInfoFromRadio_init_default
#define masterpilot_proto_RadioInfo_init_default MP_RadioInfo_init_default
#define masterpilot_proto_VTExtrinsic_init_default MP_VTExtrinsic_init_default
#define masterpilot_proto_SignedLinearValue_init_zero MP_SignedLinearValue_init_zero
#define masterpilot_proto_UnsignedLinearValue_init_zero MP_UnsignedLinearValue_init_zero
#define masterpilot_proto_VisionData_init_zero MP_VisionData_init_zero
#define masterpilot_proto_WeaponState_init_zero MP_WeaponState_init_zero
#define masterpilot_proto_ChassisState_init_zero MP_ChassisState_init_zero
#define masterpilot_proto_LegInfo_init_zero MP_LegInfo_init_zero
#define masterpilot_proto_BuffInfo_init_zero MP_BuffInfo_init_zero
#define masterpilot_proto_RobotInfoFromRadio_init_zero MP_RobotInfoFromRadio_init_zero
#define masterpilot_proto_RadioInfo_init_zero MP_RadioInfo_init_zero
#define masterpilot_proto_VTExtrinsic_init_zero MP_VTExtrinsic_init_zero

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
