/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MASTERPILOT_PROTO_MASTERPILOT_PROTO_COMMON_PB_H_INCLUDED
#define PB_MASTERPILOT_PROTO_MASTERPILOT_PROTO_COMMON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 视觉目标类型 (对应 VisionTargetType) */
typedef enum _MP_VisionTarget {
    MP_VT_NONE = 0,
    MP_VT_NORMAL = 1,
    MP_VT_SMALL_RUNE = 2,
    MP_VT_LARGE_RUNE = 3,
    MP_VT_OUTPOST = 4,
    MP_VT_BASE = 5,
    MP_VT_HERO = 6
} MP_VisionTarget;

/* 视觉自瞄状态 (对应 VisionStateType) */
typedef enum _MP_VisionState {
    MP_VS_INACTIVE = 0,
    MP_VS_ACTIVE = 1,
    MP_VS_TARGET_FOUND = 2
} MP_VisionState;

typedef enum _MP_LegMode {
    MP_LM_LOW = 0,
    MP_LM_MID = 1,
    MP_LM_HIGH = 2
} MP_LegMode;

typedef enum _MP_BuffType {
    MP_B_NONE = 0,
    MP_B_RECOVERY = 1,
    MP_B_COOLING = 2,
    MP_B_DEFENSE = 3,
    MP_B_VULNERABILITY = 4,
    MP_B_ATTACK = 5
} MP_BuffType;

/* Struct definitions */
/* 视觉状态 */
typedef struct _MP_VisionData {
    MP_VisionTarget target;
    MP_VisionState state;
} MP_VisionData;

/* 武器/发射机构状态 (对应 WeaponStatus) */
typedef struct _MP_WeaponState {
    bool fric_on;
    bool fric_online;
    float pitch; /* degree */
    float yaw; /* degree */
} MP_WeaponState;

typedef struct _MP_ChassisModeFlags {
    bool top_flag; /* 陀螺模式 */
    bool upstep_flag; /* 上台阶模式 */
    bool fly_flag; /* 飞坡模式 */
    bool jump_flag; /* 跳跃模式 */
} MP_ChassisModeFlags;

/* 底盘实时状态 (对应 ChassisStatus 部分字段) */
typedef struct _MP_ChassisState {
    float speed; /* m/s */
    float theta; /* 摆角 degree */
    float yaw_offset; /* degree */
    float pitch; /* degree */
    float roll; /* degree */
    bool has_mode_flags;
    MP_ChassisModeFlags mode_flags;
} MP_ChassisState;

/* 能源与电容状态 */
typedef struct _MP_PowerState {
    float cap_voltage_ratio; /* 电容电压比 */
} MP_PowerState;

typedef struct _MP_BuffInfo {
    MP_BuffType type;
    uint32_t strength; /* 参考官方通信手册里说的值. 0x0204 */
} MP_BuffInfo;

typedef struct _MP_RobotInfoFromRadio {
    uint32_t id; /* 一位数机器人编号 */
    uint32_t health; /* 血量 */
    uint32_t ammo; /* 剩余发弹量 */
    pb_size_t buffs_count;
    MP_BuffInfo buffs[6];
} MP_RobotInfoFromRadio;

/* 雷达无线电解密 */
typedef struct _MP_RadioInfo {
    uint32_t enemy_current_eco; /* 对方剩余经济 */
    uint32_t enemy_total_eco; /* 对方总经济 */
    uint32_t rfid; /* 对方一大堆RFID的状态 0x0a04 */
    pb_size_t enemy_robots_count;
    MP_RobotInfoFromRadio enemy_robots[6]; /* 对方机器人信息 */
} MP_RadioInfo;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _MP_VisionTarget_MIN MP_VT_NONE
#define _MP_VisionTarget_MAX MP_VT_HERO
#define _MP_VisionTarget_ARRAYSIZE ((MP_VisionTarget)(MP_VT_HERO+1))
#define MP_VisionTarget_VT_NONE MP_VT_NONE
#define MP_VisionTarget_VT_NORMAL MP_VT_NORMAL
#define MP_VisionTarget_VT_SMALL_RUNE MP_VT_SMALL_RUNE
#define MP_VisionTarget_VT_LARGE_RUNE MP_VT_LARGE_RUNE
#define MP_VisionTarget_VT_OUTPOST MP_VT_OUTPOST
#define MP_VisionTarget_VT_BASE MP_VT_BASE
#define MP_VisionTarget_VT_HERO MP_VT_HERO

#define _MP_VisionState_MIN MP_VS_INACTIVE
#define _MP_VisionState_MAX MP_VS_TARGET_FOUND
#define _MP_VisionState_ARRAYSIZE ((MP_VisionState)(MP_VS_TARGET_FOUND+1))
#define MP_VisionState_VS_INACTIVE MP_VS_INACTIVE
#define MP_VisionState_VS_ACTIVE MP_VS_ACTIVE
#define MP_VisionState_VS_TARGET_FOUND MP_VS_TARGET_FOUND

#define _MP_LegMode_MIN MP_LM_LOW
#define _MP_LegMode_MAX MP_LM_HIGH
#define _MP_LegMode_ARRAYSIZE ((MP_LegMode)(MP_LM_HIGH+1))
#define MP_LegMode_LM_LOW MP_LM_LOW
#define MP_LegMode_LM_MID MP_LM_MID
#define MP_LegMode_LM_HIGH MP_LM_HIGH

#define _MP_BuffType_MIN MP_B_NONE
#define _MP_BuffType_MAX MP_B_ATTACK
#define _MP_BuffType_ARRAYSIZE ((MP_BuffType)(MP_B_ATTACK+1))
#define MP_BuffType_B_NONE MP_B_NONE
#define MP_BuffType_B_RECOVERY MP_B_RECOVERY
#define MP_BuffType_B_COOLING MP_B_COOLING
#define MP_BuffType_B_DEFENSE MP_B_DEFENSE
#define MP_BuffType_B_VULNERABILITY MP_B_VULNERABILITY
#define MP_BuffType_B_ATTACK MP_B_ATTACK

#define MP_VisionData_target_ENUMTYPE MP_VisionTarget
#define MP_VisionData_state_ENUMTYPE MP_VisionState





#define MP_BuffInfo_type_ENUMTYPE MP_BuffType




/* Initializer values for message structs */
#define MP_VisionData_init_default               {_MP_VisionTarget_MIN, _MP_VisionState_MIN}
#define MP_WeaponState_init_default              {0, 0, 0, 0}
#define MP_ChassisModeFlags_init_default         {0, 0, 0, 0}
#define MP_ChassisState_init_default             {0, 0, 0, 0, 0, false, MP_ChassisModeFlags_init_default}
#define MP_PowerState_init_default               {0}
#define MP_BuffInfo_init_default                 {_MP_BuffType_MIN, 0}
#define MP_RobotInfoFromRadio_init_default       {0, 0, 0, 0, {MP_BuffInfo_init_default, MP_BuffInfo_init_default, MP_BuffInfo_init_default, MP_BuffInfo_init_default, MP_BuffInfo_init_default, MP_BuffInfo_init_default}}
#define MP_RadioInfo_init_default                {0, 0, 0, 0, {MP_RobotInfoFromRadio_init_default, MP_RobotInfoFromRadio_init_default, MP_RobotInfoFromRadio_init_default, MP_RobotInfoFromRadio_init_default, MP_RobotInfoFromRadio_init_default, MP_RobotInfoFromRadio_init_default}}
#define MP_VisionData_init_zero                  {_MP_VisionTarget_MIN, _MP_VisionState_MIN}
#define MP_WeaponState_init_zero                 {0, 0, 0, 0}
#define MP_ChassisModeFlags_init_zero            {0, 0, 0, 0}
#define MP_ChassisState_init_zero                {0, 0, 0, 0, 0, false, MP_ChassisModeFlags_init_zero}
#define MP_PowerState_init_zero                  {0}
#define MP_BuffInfo_init_zero                    {_MP_BuffType_MIN, 0}
#define MP_RobotInfoFromRadio_init_zero          {0, 0, 0, 0, {MP_BuffInfo_init_zero, MP_BuffInfo_init_zero, MP_BuffInfo_init_zero, MP_BuffInfo_init_zero, MP_BuffInfo_init_zero, MP_BuffInfo_init_zero}}
#define MP_RadioInfo_init_zero                   {0, 0, 0, 0, {MP_RobotInfoFromRadio_init_zero, MP_RobotInfoFromRadio_init_zero, MP_RobotInfoFromRadio_init_zero, MP_RobotInfoFromRadio_init_zero, MP_RobotInfoFromRadio_init_zero, MP_RobotInfoFromRadio_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define MP_VisionData_target_tag                 1
#define MP_VisionData_state_tag                  2
#define MP_WeaponState_fric_on_tag               1
#define MP_WeaponState_fric_online_tag           2
#define MP_WeaponState_pitch_tag                 4
#define MP_WeaponState_yaw_tag                   5
#define MP_ChassisModeFlags_top_flag_tag         1
#define MP_ChassisModeFlags_upstep_flag_tag      2
#define MP_ChassisModeFlags_fly_flag_tag         3
#define MP_ChassisModeFlags_jump_flag_tag        4
#define MP_ChassisState_speed_tag                1
#define MP_ChassisState_theta_tag                2
#define MP_ChassisState_yaw_offset_tag           3
#define MP_ChassisState_pitch_tag                4
#define MP_ChassisState_roll_tag                 5
#define MP_ChassisState_mode_flags_tag           6
#define MP_PowerState_cap_voltage_ratio_tag      1
#define MP_BuffInfo_type_tag                     1
#define MP_BuffInfo_strength_tag                 2
#define MP_RobotInfoFromRadio_id_tag             1
#define MP_RobotInfoFromRadio_health_tag         2
#define MP_RobotInfoFromRadio_ammo_tag           3
#define MP_RobotInfoFromRadio_buffs_tag          6
#define MP_RadioInfo_enemy_current_eco_tag       1
#define MP_RadioInfo_enemy_total_eco_tag         2
#define MP_RadioInfo_rfid_tag                    3
#define MP_RadioInfo_enemy_robots_tag            4

/* Struct field encoding specification for nanopb */
#define MP_VisionData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    target,            1) \
X(a, STATIC,   SINGULAR, UENUM,    state,             2)
#define MP_VisionData_CALLBACK NULL
#define MP_VisionData_DEFAULT NULL

#define MP_WeaponState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     fric_on,           1) \
X(a, STATIC,   SINGULAR, BOOL,     fric_online,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    pitch,             4) \
X(a, STATIC,   SINGULAR, FLOAT,    yaw,               5)
#define MP_WeaponState_CALLBACK NULL
#define MP_WeaponState_DEFAULT NULL

#define MP_ChassisModeFlags_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     top_flag,          1) \
X(a, STATIC,   SINGULAR, BOOL,     upstep_flag,       2) \
X(a, STATIC,   SINGULAR, BOOL,     fly_flag,          3) \
X(a, STATIC,   SINGULAR, BOOL,     jump_flag,         4)
#define MP_ChassisModeFlags_CALLBACK NULL
#define MP_ChassisModeFlags_DEFAULT NULL

#define MP_ChassisState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    theta,             2) \
X(a, STATIC,   SINGULAR, FLOAT,    yaw_offset,        3) \
X(a, STATIC,   SINGULAR, FLOAT,    pitch,             4) \
X(a, STATIC,   SINGULAR, FLOAT,    roll,              5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mode_flags,        6)
#define MP_ChassisState_CALLBACK NULL
#define MP_ChassisState_DEFAULT NULL
#define MP_ChassisState_mode_flags_MSGTYPE MP_ChassisModeFlags

#define MP_PowerState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    cap_voltage_ratio,   1)
#define MP_PowerState_CALLBACK NULL
#define MP_PowerState_DEFAULT NULL

#define MP_BuffInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, UINT32,   strength,          2)
#define MP_BuffInfo_CALLBACK NULL
#define MP_BuffInfo_DEFAULT NULL

#define MP_RobotInfoFromRadio_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, UINT32,   health,            2) \
X(a, STATIC,   SINGULAR, UINT32,   ammo,              3) \
X(a, STATIC,   REPEATED, MESSAGE,  buffs,             6)
#define MP_RobotInfoFromRadio_CALLBACK NULL
#define MP_RobotInfoFromRadio_DEFAULT NULL
#define MP_RobotInfoFromRadio_buffs_MSGTYPE MP_BuffInfo

#define MP_RadioInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   enemy_current_eco,   1) \
X(a, STATIC,   SINGULAR, UINT32,   enemy_total_eco,   2) \
X(a, STATIC,   SINGULAR, UINT32,   rfid,              3) \
X(a, STATIC,   REPEATED, MESSAGE,  enemy_robots,      4)
#define MP_RadioInfo_CALLBACK NULL
#define MP_RadioInfo_DEFAULT NULL
#define MP_RadioInfo_enemy_robots_MSGTYPE MP_RobotInfoFromRadio

extern const pb_msgdesc_t MP_VisionData_msg;
extern const pb_msgdesc_t MP_WeaponState_msg;
extern const pb_msgdesc_t MP_ChassisModeFlags_msg;
extern const pb_msgdesc_t MP_ChassisState_msg;
extern const pb_msgdesc_t MP_PowerState_msg;
extern const pb_msgdesc_t MP_BuffInfo_msg;
extern const pb_msgdesc_t MP_RobotInfoFromRadio_msg;
extern const pb_msgdesc_t MP_RadioInfo_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MP_VisionData_fields &MP_VisionData_msg
#define MP_WeaponState_fields &MP_WeaponState_msg
#define MP_ChassisModeFlags_fields &MP_ChassisModeFlags_msg
#define MP_ChassisState_fields &MP_ChassisState_msg
#define MP_PowerState_fields &MP_PowerState_msg
#define MP_BuffInfo_fields &MP_BuffInfo_msg
#define MP_RobotInfoFromRadio_fields &MP_RobotInfoFromRadio_msg
#define MP_RadioInfo_fields &MP_RadioInfo_msg

/* Maximum encoded size of messages (where known) */
#define MASTERPILOT_PROTO_MASTERPILOT_PROTO_COMMON_PB_H_MAX_SIZE MP_RadioInfo_size
#define MP_BuffInfo_size                         8
#define MP_ChassisModeFlags_size                 8
#define MP_ChassisState_size                     35
#define MP_PowerState_size                       5
#define MP_RadioInfo_size                        498
#define MP_RobotInfoFromRadio_size               78
#define MP_VisionData_size                       4
#define MP_WeaponState_size                      14

/* Mapping from canonical names (mangle_names or overridden package name) */
#define masterpilot_proto_VisionTarget MP_VisionTarget
#define masterpilot_proto_VisionState MP_VisionState
#define masterpilot_proto_LegMode MP_LegMode
#define masterpilot_proto_BuffType MP_BuffType
#define masterpilot_proto_VisionData MP_VisionData
#define masterpilot_proto_WeaponState MP_WeaponState
#define masterpilot_proto_ChassisModeFlags MP_ChassisModeFlags
#define masterpilot_proto_ChassisState MP_ChassisState
#define masterpilot_proto_PowerState MP_PowerState
#define masterpilot_proto_BuffInfo MP_BuffInfo
#define masterpilot_proto_RobotInfoFromRadio MP_RobotInfoFromRadio
#define masterpilot_proto_RadioInfo MP_RadioInfo
#define _masterpilot_proto_VisionTarget_MIN _MP_VisionTarget_MIN
#define _masterpilot_proto_VisionTarget_MAX _MP_VisionTarget_MAX
#define _masterpilot_proto_VisionTarget_ARRAYSIZE _MP_VisionTarget_ARRAYSIZE
#define _masterpilot_proto_VisionState_MIN _MP_VisionState_MIN
#define _masterpilot_proto_VisionState_MAX _MP_VisionState_MAX
#define _masterpilot_proto_VisionState_ARRAYSIZE _MP_VisionState_ARRAYSIZE
#define _masterpilot_proto_LegMode_MIN _MP_LegMode_MIN
#define _masterpilot_proto_LegMode_MAX _MP_LegMode_MAX
#define _masterpilot_proto_LegMode_ARRAYSIZE _MP_LegMode_ARRAYSIZE
#define _masterpilot_proto_BuffType_MIN _MP_BuffType_MIN
#define _masterpilot_proto_BuffType_MAX _MP_BuffType_MAX
#define _masterpilot_proto_BuffType_ARRAYSIZE _MP_BuffType_ARRAYSIZE
#define masterpilot_proto_VisionData_init_default MP_VisionData_init_default
#define masterpilot_proto_WeaponState_init_default MP_WeaponState_init_default
#define masterpilot_proto_ChassisModeFlags_init_default MP_ChassisModeFlags_init_default
#define masterpilot_proto_ChassisState_init_default MP_ChassisState_init_default
#define masterpilot_proto_PowerState_init_default MP_PowerState_init_default
#define masterpilot_proto_BuffInfo_init_default MP_BuffInfo_init_default
#define masterpilot_proto_RobotInfoFromRadio_init_default MP_RobotInfoFromRadio_init_default
#define masterpilot_proto_RadioInfo_init_default MP_RadioInfo_init_default
#define masterpilot_proto_VisionData_init_zero MP_VisionData_init_zero
#define masterpilot_proto_WeaponState_init_zero MP_WeaponState_init_zero
#define masterpilot_proto_ChassisModeFlags_init_zero MP_ChassisModeFlags_init_zero
#define masterpilot_proto_ChassisState_init_zero MP_ChassisState_init_zero
#define masterpilot_proto_PowerState_init_zero MP_PowerState_init_zero
#define masterpilot_proto_BuffInfo_init_zero MP_BuffInfo_init_zero
#define masterpilot_proto_RobotInfoFromRadio_init_zero MP_RobotInfoFromRadio_init_zero
#define masterpilot_proto_RadioInfo_init_zero MP_RadioInfo_init_zero

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
