/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MASTERPILOT_PROTO_MASTERPILOT_PROTO_CUSTOM_CONTROL_PB_H_INCLUDED
#define PB_MASTERPILOT_PROTO_MASTERPILOT_PROTO_CUSTOM_CONTROL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* 速度线性量 */
typedef struct _MP_SpeedFactor {
    /* X轴速度比例 (0~255, 255为满速, 0为静止, 无负数) */
    uint32_t x;
    /* Y轴速度比例 (0~255, 255为满速, 0为静止, 无负数) */
    uint32_t y;
} MP_SpeedFactor;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define MP_SpeedFactor_init_default              {0, 0}
#define MP_SpeedFactor_init_zero                 {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MP_SpeedFactor_x_tag                     1
#define MP_SpeedFactor_y_tag                     2

/* Struct field encoding specification for nanopb */
#define MP_SpeedFactor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   x,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   y,                 2)
#define MP_SpeedFactor_CALLBACK NULL
#define MP_SpeedFactor_DEFAULT NULL

extern const pb_msgdesc_t MP_SpeedFactor_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MP_SpeedFactor_fields &MP_SpeedFactor_msg

/* Maximum encoded size of messages (where known) */
#define MASTERPILOT_PROTO_MASTERPILOT_PROTO_CUSTOM_CONTROL_PB_H_MAX_SIZE MP_SpeedFactor_size
#define MP_SpeedFactor_size                      12

/* Mapping from canonical names (mangle_names or overridden package name) */
#define masterpilot_proto_SpeedFactor MP_SpeedFactor
#define masterpilot_proto_SpeedFactor_init_default MP_SpeedFactor_init_default
#define masterpilot_proto_SpeedFactor_init_zero MP_SpeedFactor_init_zero

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
