/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MASTERPILOT_PROTO_MASTERPILOT_PROTO_DRONE_PB_H_INCLUDED
#define PB_MASTERPILOT_PROTO_MASTERPILOT_PROTO_DRONE_PB_H_INCLUDED
#include <pb.h>
#include "masterpilot/proto/common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _MP_PidMode {
    MP_PM_INACTIVE = 0,
    MP_PM_MEC = 1,
    MP_PM_GYRO = 2,
    MP_PM_VISION = 3
} MP_PidMode;

typedef enum _MP_LampCmd {
    MP_LC_IDLE = 0,
    MP_LC_RC_OFFLINE = 1,
    MP_LC_AWAIT = 2,
    MP_LC_BASE = 3,
    MP_LC_OUTPOST = 4,
    MP_LC_BUF = 5,
    MP_LC_FORWARD = 6,
    MP_LC_BACK = 7,
    MP_LC_LEFT = 8,
    MP_LC_RIGHT = 9,
    MP_LC_CW_SPIN = 10,
    MP_LC_CCW_SPIN = 11,
    MP_LC_UP = 12,
    MP_LC_DOWN = 13
} MP_LampCmd;

/* Struct definitions */
typedef struct _MP_DroneDataPacketToClient {
    bool has_weapon;
    MP_WeaponState weapon;
    bool has_vision;
    MP_VisionData vision;
    bool has_lamp;
    MP_LampCmd lamp;
    bool has_pid;
    MP_PidMode pid;
    bool has_radio_info;
    MP_RadioInfo radio_info;
} MP_DroneDataPacketToClient;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _MP_PidMode_MIN MP_PM_INACTIVE
#define _MP_PidMode_MAX MP_PM_VISION
#define _MP_PidMode_ARRAYSIZE ((MP_PidMode)(MP_PM_VISION+1))
#define MP_PidMode_PM_INACTIVE MP_PM_INACTIVE
#define MP_PidMode_PM_MEC MP_PM_MEC
#define MP_PidMode_PM_GYRO MP_PM_GYRO
#define MP_PidMode_PM_VISION MP_PM_VISION

#define _MP_LampCmd_MIN MP_LC_IDLE
#define _MP_LampCmd_MAX MP_LC_DOWN
#define _MP_LampCmd_ARRAYSIZE ((MP_LampCmd)(MP_LC_DOWN+1))
#define MP_LampCmd_LC_IDLE MP_LC_IDLE
#define MP_LampCmd_LC_RC_OFFLINE MP_LC_RC_OFFLINE
#define MP_LampCmd_LC_AWAIT MP_LC_AWAIT
#define MP_LampCmd_LC_BASE MP_LC_BASE
#define MP_LampCmd_LC_OUTPOST MP_LC_OUTPOST
#define MP_LampCmd_LC_BUF MP_LC_BUF
#define MP_LampCmd_LC_FORWARD MP_LC_FORWARD
#define MP_LampCmd_LC_BACK MP_LC_BACK
#define MP_LampCmd_LC_LEFT MP_LC_LEFT
#define MP_LampCmd_LC_RIGHT MP_LC_RIGHT
#define MP_LampCmd_LC_CW_SPIN MP_LC_CW_SPIN
#define MP_LampCmd_LC_CCW_SPIN MP_LC_CCW_SPIN
#define MP_LampCmd_LC_UP MP_LC_UP
#define MP_LampCmd_LC_DOWN MP_LC_DOWN

#define MP_DroneDataPacketToClient_lamp_ENUMTYPE MP_LampCmd
#define MP_DroneDataPacketToClient_pid_ENUMTYPE MP_PidMode


/* Initializer values for message structs */
#define MP_DroneDataPacketToClient_init_default  {false, MP_WeaponState_init_default, false, MP_VisionData_init_default, false, _MP_LampCmd_MIN, false, _MP_PidMode_MIN, false, MP_RadioInfo_init_default}
#define MP_DroneDataPacketToClient_init_zero     {false, MP_WeaponState_init_zero, false, MP_VisionData_init_zero, false, _MP_LampCmd_MIN, false, _MP_PidMode_MIN, false, MP_RadioInfo_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define MP_DroneDataPacketToClient_weapon_tag    1
#define MP_DroneDataPacketToClient_vision_tag    2
#define MP_DroneDataPacketToClient_lamp_tag      3
#define MP_DroneDataPacketToClient_pid_tag       4
#define MP_DroneDataPacketToClient_radio_info_tag 8

/* Struct field encoding specification for nanopb */
#define MP_DroneDataPacketToClient_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  weapon,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  vision,            2) \
X(a, STATIC,   OPTIONAL, UENUM,    lamp,              3) \
X(a, STATIC,   OPTIONAL, UENUM,    pid,               4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  radio_info,        8)
#define MP_DroneDataPacketToClient_CALLBACK NULL
#define MP_DroneDataPacketToClient_DEFAULT NULL
#define MP_DroneDataPacketToClient_weapon_MSGTYPE MP_WeaponState
#define MP_DroneDataPacketToClient_vision_MSGTYPE MP_VisionData
#define MP_DroneDataPacketToClient_radio_info_MSGTYPE MP_RadioInfo

extern const pb_msgdesc_t MP_DroneDataPacketToClient_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MP_DroneDataPacketToClient_fields &MP_DroneDataPacketToClient_msg

/* Maximum encoded size of messages (where known) */
#define MASTERPILOT_PROTO_MASTERPILOT_PROTO_DRONE_PB_H_MAX_SIZE MP_DroneDataPacketToClient_size
#define MP_DroneDataPacketToClient_size          527

/* Mapping from canonical names (mangle_names or overridden package name) */
#define masterpilot_proto_PidMode MP_PidMode
#define masterpilot_proto_LampCmd MP_LampCmd
#define masterpilot_proto_DroneDataPacketToClient MP_DroneDataPacketToClient
#define _masterpilot_proto_PidMode_MIN _MP_PidMode_MIN
#define _masterpilot_proto_PidMode_MAX _MP_PidMode_MAX
#define _masterpilot_proto_PidMode_ARRAYSIZE _MP_PidMode_ARRAYSIZE
#define _masterpilot_proto_LampCmd_MIN _MP_LampCmd_MIN
#define _masterpilot_proto_LampCmd_MAX _MP_LampCmd_MAX
#define _masterpilot_proto_LampCmd_ARRAYSIZE _MP_LampCmd_ARRAYSIZE
#define masterpilot_proto_DroneDataPacketToClient_init_default MP_DroneDataPacketToClient_init_default
#define masterpilot_proto_DroneDataPacketToClient_init_zero MP_DroneDataPacketToClient_init_zero

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
