/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MASTERPILOT_PROTO_MASTERPILOT_PROTO_DRONE_PB_H_INCLUDED
#define PB_MASTERPILOT_PROTO_MASTERPILOT_PROTO_DRONE_PB_H_INCLUDED
#include <pb.h>
#include "masterpilot/proto/common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _MP_DronePidMode {
    MP_DPM_INACTIVE = 0,
    MP_DPM_MEC = 1,
    MP_DPM_GYRO = 2,
    MP_DPM_VISION = 3
} MP_DronePidMode;

typedef enum _MP_DroneLampCmd {
    MP_DLC_IDLE = 0,
    MP_DLC_RC_OFFLINE = 1,
    MP_DLC_AWAIT = 2,
    MP_DLC_BASE = 3,
    MP_DLC_OUTPOST = 4,
    MP_DLC_BUF = 5,
    MP_DLC_FORWARD = 6,
    MP_DLC_BACK = 7,
    MP_DLC_LEFT = 8,
    MP_DLC_RIGHT = 9,
    MP_DLC_CW_SPIN = 10,
    MP_DLC_CCW_SPIN = 11,
    MP_DLC_UP = 12,
    MP_DLC_DOWN = 13
} MP_DroneLampCmd;

/* Struct definitions */
typedef struct _MP_DroneDataPacketToClient {
    bool has_weapon;
    MP_WeaponState weapon;
    bool has_vision;
    MP_VisionData vision;
    bool has_lamp;
    MP_DroneLampCmd lamp;
    bool has_pid;
    MP_DronePidMode pid;
    bool has_radio_info;
    MP_RadioInfo radio_info;
    bool has_vt_extrinsic;
    MP_VTExtrinsic vt_extrinsic;
} MP_DroneDataPacketToClient;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _MP_DronePidMode_MIN MP_DPM_INACTIVE
#define _MP_DronePidMode_MAX MP_DPM_VISION
#define _MP_DronePidMode_ARRAYSIZE ((MP_DronePidMode)(MP_DPM_VISION+1))
#define MP_DronePidMode_DPM_INACTIVE MP_DPM_INACTIVE
#define MP_DronePidMode_DPM_MEC MP_DPM_MEC
#define MP_DronePidMode_DPM_GYRO MP_DPM_GYRO
#define MP_DronePidMode_DPM_VISION MP_DPM_VISION

#define _MP_DroneLampCmd_MIN MP_DLC_IDLE
#define _MP_DroneLampCmd_MAX MP_DLC_DOWN
#define _MP_DroneLampCmd_ARRAYSIZE ((MP_DroneLampCmd)(MP_DLC_DOWN+1))
#define MP_DroneLampCmd_DLC_IDLE MP_DLC_IDLE
#define MP_DroneLampCmd_DLC_RC_OFFLINE MP_DLC_RC_OFFLINE
#define MP_DroneLampCmd_DLC_AWAIT MP_DLC_AWAIT
#define MP_DroneLampCmd_DLC_BASE MP_DLC_BASE
#define MP_DroneLampCmd_DLC_OUTPOST MP_DLC_OUTPOST
#define MP_DroneLampCmd_DLC_BUF MP_DLC_BUF
#define MP_DroneLampCmd_DLC_FORWARD MP_DLC_FORWARD
#define MP_DroneLampCmd_DLC_BACK MP_DLC_BACK
#define MP_DroneLampCmd_DLC_LEFT MP_DLC_LEFT
#define MP_DroneLampCmd_DLC_RIGHT MP_DLC_RIGHT
#define MP_DroneLampCmd_DLC_CW_SPIN MP_DLC_CW_SPIN
#define MP_DroneLampCmd_DLC_CCW_SPIN MP_DLC_CCW_SPIN
#define MP_DroneLampCmd_DLC_UP MP_DLC_UP
#define MP_DroneLampCmd_DLC_DOWN MP_DLC_DOWN

#define MP_DroneDataPacketToClient_lamp_ENUMTYPE MP_DroneLampCmd
#define MP_DroneDataPacketToClient_pid_ENUMTYPE MP_DronePidMode


/* Initializer values for message structs */
#define MP_DroneDataPacketToClient_init_default  {false, MP_WeaponState_init_default, false, MP_VisionData_init_default, false, _MP_DroneLampCmd_MIN, false, _MP_DronePidMode_MIN, false, MP_RadioInfo_init_default, false, MP_VTExtrinsic_init_default}
#define MP_DroneDataPacketToClient_init_zero     {false, MP_WeaponState_init_zero, false, MP_VisionData_init_zero, false, _MP_DroneLampCmd_MIN, false, _MP_DronePidMode_MIN, false, MP_RadioInfo_init_zero, false, MP_VTExtrinsic_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define MP_DroneDataPacketToClient_weapon_tag    1
#define MP_DroneDataPacketToClient_vision_tag    2
#define MP_DroneDataPacketToClient_lamp_tag      3
#define MP_DroneDataPacketToClient_pid_tag       4
#define MP_DroneDataPacketToClient_radio_info_tag 8
#define MP_DroneDataPacketToClient_vt_extrinsic_tag 9

/* Struct field encoding specification for nanopb */
#define MP_DroneDataPacketToClient_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  weapon,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  vision,            2) \
X(a, STATIC,   OPTIONAL, UENUM,    lamp,              3) \
X(a, STATIC,   OPTIONAL, UENUM,    pid,               4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  radio_info,        8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  vt_extrinsic,      9)
#define MP_DroneDataPacketToClient_CALLBACK NULL
#define MP_DroneDataPacketToClient_DEFAULT NULL
#define MP_DroneDataPacketToClient_weapon_MSGTYPE MP_WeaponState
#define MP_DroneDataPacketToClient_vision_MSGTYPE MP_VisionData
#define MP_DroneDataPacketToClient_radio_info_MSGTYPE MP_RadioInfo
#define MP_DroneDataPacketToClient_vt_extrinsic_MSGTYPE MP_VTExtrinsic

extern const pb_msgdesc_t MP_DroneDataPacketToClient_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MP_DroneDataPacketToClient_fields &MP_DroneDataPacketToClient_msg

/* Maximum encoded size of messages (where known) */
#define MASTERPILOT_PROTO_MASTERPILOT_PROTO_DRONE_PB_H_MAX_SIZE MP_DroneDataPacketToClient_size
#define MP_DroneDataPacketToClient_size          562

/* Mapping from canonical names (mangle_names or overridden package name) */
#define masterpilot_proto_DronePidMode MP_DronePidMode
#define masterpilot_proto_DroneLampCmd MP_DroneLampCmd
#define masterpilot_proto_DroneDataPacketToClient MP_DroneDataPacketToClient
#define _masterpilot_proto_DronePidMode_MIN _MP_DronePidMode_MIN
#define _masterpilot_proto_DronePidMode_MAX _MP_DronePidMode_MAX
#define _masterpilot_proto_DronePidMode_ARRAYSIZE _MP_DronePidMode_ARRAYSIZE
#define _masterpilot_proto_DroneLampCmd_MIN _MP_DroneLampCmd_MIN
#define _masterpilot_proto_DroneLampCmd_MAX _MP_DroneLampCmd_MAX
#define _masterpilot_proto_DroneLampCmd_ARRAYSIZE _MP_DroneLampCmd_ARRAYSIZE
#define masterpilot_proto_DroneDataPacketToClient_init_default MP_DroneDataPacketToClient_init_default
#define masterpilot_proto_DroneDataPacketToClient_init_zero MP_DroneDataPacketToClient_init_zero

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
