/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MASTERPILOT_PROTO_MASTERPILOT_PROTO_ENGINEER_PB_H_INCLUDED
#define PB_MASTERPILOT_PROTO_MASTERPILOT_PROTO_ENGINEER_PB_H_INCLUDED
#include <pb.h>
#include "masterpilot/proto/common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 系统控制流程状态 */
typedef enum _MP_AutoProcess {
    MP_AP_NONE = 0,
    MP_AP_RETURN_ORIGIN = 1,
    MP_AP_CLIMBING = 2,
    MP_AP_DOWN_STAIR = 3,
    MP_AP_ENERGY_UNIT = 4,
    MP_AP_EXCHANGE_ORE = 5,
    MP_AP_STORE_ORE = 6,
    MP_AP_GROUND_ORE = 7
} MP_AutoProcess;

/* 控制模式 */
typedef enum _MP_ControlMode {
    MP_CM_NONE = 0,
    MP_CM_RC = 1,
    MP_CM_KEYBOARD = 2,
    MP_CM_CONTROLLER = 3
} MP_ControlMode;

/* Struct definitions */
/* 机械臂实时数据 */
typedef struct _MP_ArmState {
    float angle_yaw; /* 机械臂Yaw */
    float angle_pitch1; /* 关节1 Pitch */
    float angle_pitch2; /* 关节2 Pitch */
    float angle_pitch3; /* 关节3 Pitch */
    float angle_roll; /* 机械臂Roll */
    float angle_end_pitch; /* 末端Pitch */
    float angle_end_roll; /* 末端Roll */
    float length_grip; /* 夹爪开合距离 */
    bool grip_close; /* 夹爪闭合标志位 */
} MP_ArmState;

/* 机器人全局标志位与裁判系统数据 */
typedef struct _MP_RobotStatus {
    bool p3_lock; /* P3锁定标志 */
    bool robot_init_ok; /* 初始化完成 */
    bool controlled_by_controller; /* 是否被遥控器控制 */
} MP_RobotStatus;

/* 发送给自定义客户端的大包 */
typedef struct _MP_EngineerDataPacketToClient {
    bool has_current_process;
    MP_AutoProcess current_process;
    bool has_ctrl_mode;
    MP_ControlMode ctrl_mode;
    bool has_chassis;
    MP_ChassisState chassis;
    bool has_arm;
    MP_ArmState arm;
    bool has_weapon;
    MP_WeaponState weapon;
    bool has_vision;
    MP_VisionData vision;
    bool has_status;
    MP_RobotStatus status;
    bool has_radio_info;
    MP_RadioInfo radio_info;
} MP_EngineerDataPacketToClient;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _MP_AutoProcess_MIN MP_AP_NONE
#define _MP_AutoProcess_MAX MP_AP_GROUND_ORE
#define _MP_AutoProcess_ARRAYSIZE ((MP_AutoProcess)(MP_AP_GROUND_ORE+1))
#define MP_AutoProcess_AP_NONE MP_AP_NONE
#define MP_AutoProcess_AP_RETURN_ORIGIN MP_AP_RETURN_ORIGIN
#define MP_AutoProcess_AP_CLIMBING MP_AP_CLIMBING
#define MP_AutoProcess_AP_DOWN_STAIR MP_AP_DOWN_STAIR
#define MP_AutoProcess_AP_ENERGY_UNIT MP_AP_ENERGY_UNIT
#define MP_AutoProcess_AP_EXCHANGE_ORE MP_AP_EXCHANGE_ORE
#define MP_AutoProcess_AP_STORE_ORE MP_AP_STORE_ORE
#define MP_AutoProcess_AP_GROUND_ORE MP_AP_GROUND_ORE

#define _MP_ControlMode_MIN MP_CM_NONE
#define _MP_ControlMode_MAX MP_CM_CONTROLLER
#define _MP_ControlMode_ARRAYSIZE ((MP_ControlMode)(MP_CM_CONTROLLER+1))
#define MP_ControlMode_CM_NONE MP_CM_NONE
#define MP_ControlMode_CM_RC MP_CM_RC
#define MP_ControlMode_CM_KEYBOARD MP_CM_KEYBOARD
#define MP_ControlMode_CM_CONTROLLER MP_CM_CONTROLLER



#define MP_EngineerDataPacketToClient_current_process_ENUMTYPE MP_AutoProcess
#define MP_EngineerDataPacketToClient_ctrl_mode_ENUMTYPE MP_ControlMode


/* Initializer values for message structs */
#define MP_ArmState_init_default                 {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define MP_RobotStatus_init_default              {0, 0, 0}
#define MP_EngineerDataPacketToClient_init_default {false, _MP_AutoProcess_MIN, false, _MP_ControlMode_MIN, false, MP_ChassisState_init_default, false, MP_ArmState_init_default, false, MP_WeaponState_init_default, false, MP_VisionData_init_default, false, MP_RobotStatus_init_default, false, MP_RadioInfo_init_default}
#define MP_ArmState_init_zero                    {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define MP_RobotStatus_init_zero                 {0, 0, 0}
#define MP_EngineerDataPacketToClient_init_zero  {false, _MP_AutoProcess_MIN, false, _MP_ControlMode_MIN, false, MP_ChassisState_init_zero, false, MP_ArmState_init_zero, false, MP_WeaponState_init_zero, false, MP_VisionData_init_zero, false, MP_RobotStatus_init_zero, false, MP_RadioInfo_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define MP_ArmState_angle_yaw_tag                1
#define MP_ArmState_angle_pitch1_tag             2
#define MP_ArmState_angle_pitch2_tag             3
#define MP_ArmState_angle_pitch3_tag             4
#define MP_ArmState_angle_roll_tag               5
#define MP_ArmState_angle_end_pitch_tag          6
#define MP_ArmState_angle_end_roll_tag           7
#define MP_ArmState_length_grip_tag              8
#define MP_ArmState_grip_close_tag               9
#define MP_RobotStatus_p3_lock_tag               1
#define MP_RobotStatus_robot_init_ok_tag         2
#define MP_RobotStatus_controlled_by_controller_tag 3
#define MP_EngineerDataPacketToClient_current_process_tag 1
#define MP_EngineerDataPacketToClient_ctrl_mode_tag 2
#define MP_EngineerDataPacketToClient_chassis_tag 3
#define MP_EngineerDataPacketToClient_arm_tag    4
#define MP_EngineerDataPacketToClient_weapon_tag 5
#define MP_EngineerDataPacketToClient_vision_tag 6
#define MP_EngineerDataPacketToClient_status_tag 7
#define MP_EngineerDataPacketToClient_radio_info_tag 8

/* Struct field encoding specification for nanopb */
#define MP_ArmState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_yaw,         1) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_pitch1,      2) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_pitch2,      3) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_pitch3,      4) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_roll,        5) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_end_pitch,   6) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_end_roll,    7) \
X(a, STATIC,   SINGULAR, FLOAT,    length_grip,       8) \
X(a, STATIC,   SINGULAR, BOOL,     grip_close,        9)
#define MP_ArmState_CALLBACK NULL
#define MP_ArmState_DEFAULT NULL

#define MP_RobotStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     p3_lock,           1) \
X(a, STATIC,   SINGULAR, BOOL,     robot_init_ok,     2) \
X(a, STATIC,   SINGULAR, BOOL,     controlled_by_controller,   3)
#define MP_RobotStatus_CALLBACK NULL
#define MP_RobotStatus_DEFAULT NULL

#define MP_EngineerDataPacketToClient_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    current_process,   1) \
X(a, STATIC,   OPTIONAL, UENUM,    ctrl_mode,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  chassis,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  arm,               4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  weapon,            5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  vision,            6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  radio_info,        8)
#define MP_EngineerDataPacketToClient_CALLBACK NULL
#define MP_EngineerDataPacketToClient_DEFAULT NULL
#define MP_EngineerDataPacketToClient_chassis_MSGTYPE MP_ChassisState
#define MP_EngineerDataPacketToClient_arm_MSGTYPE MP_ArmState
#define MP_EngineerDataPacketToClient_weapon_MSGTYPE MP_WeaponState
#define MP_EngineerDataPacketToClient_vision_MSGTYPE MP_VisionData
#define MP_EngineerDataPacketToClient_status_MSGTYPE MP_RobotStatus
#define MP_EngineerDataPacketToClient_radio_info_MSGTYPE MP_RadioInfo

extern const pb_msgdesc_t MP_ArmState_msg;
extern const pb_msgdesc_t MP_RobotStatus_msg;
extern const pb_msgdesc_t MP_EngineerDataPacketToClient_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MP_ArmState_fields &MP_ArmState_msg
#define MP_RobotStatus_fields &MP_RobotStatus_msg
#define MP_EngineerDataPacketToClient_fields &MP_EngineerDataPacketToClient_msg

/* Maximum encoded size of messages (where known) */
#define MASTERPILOT_PROTO_MASTERPILOT_PROTO_ENGINEER_PB_H_MAX_SIZE MP_EngineerDataPacketToClient_size
#define MP_ArmState_size                         42
#define MP_EngineerDataPacketToClient_size       608
#define MP_RobotStatus_size                      6

/* Mapping from canonical names (mangle_names or overridden package name) */
#define masterpilot_proto_AutoProcess MP_AutoProcess
#define masterpilot_proto_ControlMode MP_ControlMode
#define masterpilot_proto_ArmState MP_ArmState
#define masterpilot_proto_RobotStatus MP_RobotStatus
#define masterpilot_proto_EngineerDataPacketToClient MP_EngineerDataPacketToClient
#define _masterpilot_proto_AutoProcess_MIN _MP_AutoProcess_MIN
#define _masterpilot_proto_AutoProcess_MAX _MP_AutoProcess_MAX
#define _masterpilot_proto_AutoProcess_ARRAYSIZE _MP_AutoProcess_ARRAYSIZE
#define _masterpilot_proto_ControlMode_MIN _MP_ControlMode_MIN
#define _masterpilot_proto_ControlMode_MAX _MP_ControlMode_MAX
#define _masterpilot_proto_ControlMode_ARRAYSIZE _MP_ControlMode_ARRAYSIZE
#define masterpilot_proto_ArmState_init_default MP_ArmState_init_default
#define masterpilot_proto_RobotStatus_init_default MP_RobotStatus_init_default
#define masterpilot_proto_EngineerDataPacketToClient_init_default MP_EngineerDataPacketToClient_init_default
#define masterpilot_proto_ArmState_init_zero MP_ArmState_init_zero
#define masterpilot_proto_RobotStatus_init_zero MP_RobotStatus_init_zero
#define masterpilot_proto_EngineerDataPacketToClient_init_zero MP_EngineerDataPacketToClient_init_zero

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
