/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MASTERPILOT_PROTO_MASTERPILOT_PROTO_ENGINEER_PB_H_INCLUDED
#define PB_MASTERPILOT_PROTO_MASTERPILOT_PROTO_ENGINEER_PB_H_INCLUDED
#include <pb.h>
#include "masterpilot/proto/common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 系统控制流程状态 */
typedef enum _MP_EngineerAutoProcessState {
    MP_EAP_NONE = 0,
    MP_EAP_RETURN_ORIGIN = 1,
    MP_EAP_CLIMBING = 2,
    MP_EAP_DOWN_STAIR = 3,
    MP_EAP_ENERGY_UNIT = 4,
    MP_EAP_EXCHANGE_ORE = 5,
    MP_EAP_STORE_ORE = 6,
    MP_EAP_GROUND_ORE = 7
} MP_EngineerAutoProcessState;

/* 控制模式 */
typedef enum _MP_EngineerControlMode {
    MP_ECM_NONE = 0,
    MP_ECM_RC = 1,
    MP_ECM_KEYBOARD = 2,
    MP_ECM_CONTROLLER = 3
} MP_EngineerControlMode;

/* Struct definitions */
/* 机械臂实时数据 */
typedef struct _MP_ArmState {
    float angle_yaw; /* 机械臂Yaw */
    float angle_pitch1; /* 关节1 Pitch */
    float angle_pitch2; /* 关节2 Pitch */
    float angle_pitch3; /* 关节3 Pitch */
    float angle_roll; /* 机械臂Roll */
    float angle_end_pitch; /* 末端Pitch */
    float angle_end_roll; /* 末端Roll */
    float length_grip; /* 夹爪开合距离 */
    bool grip_close; /* 夹爪闭合标志位 */
} MP_ArmState;

/* 机器人全局标志位与裁判系统数据 */
typedef struct _MP_EngineerStatus {
    bool p3_lock; /* P3锁定标志 */
    bool robot_init_ok; /* 初始化完成 */
    bool controlled_by_controller; /* 是否被遥控器控制 */
} MP_EngineerStatus;

/* 发送给自定义客户端的大包 */
typedef struct _MP_EngineerDataPacketToClient {
    bool has_current_process;
    MP_EngineerAutoProcessState current_process;
    bool has_ctrl_mode;
    MP_EngineerControlMode ctrl_mode;
    bool has_chassis;
    MP_ChassisState chassis;
    bool has_arm;
    MP_ArmState arm;
    bool has_weapon;
    MP_WeaponState weapon;
    bool has_vision;
    MP_VisionData vision;
    bool has_status;
    MP_EngineerStatus status;
    bool has_radio_info;
    MP_RadioInfo radio_info;
    bool has_vt_extrinsic;
    MP_VTExtrinsic vt_extrinsic;
} MP_EngineerDataPacketToClient;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _MP_EngineerAutoProcessState_MIN MP_EAP_NONE
#define _MP_EngineerAutoProcessState_MAX MP_EAP_GROUND_ORE
#define _MP_EngineerAutoProcessState_ARRAYSIZE ((MP_EngineerAutoProcessState)(MP_EAP_GROUND_ORE+1))
#define MP_EngineerAutoProcessState_EAP_NONE MP_EAP_NONE
#define MP_EngineerAutoProcessState_EAP_RETURN_ORIGIN MP_EAP_RETURN_ORIGIN
#define MP_EngineerAutoProcessState_EAP_CLIMBING MP_EAP_CLIMBING
#define MP_EngineerAutoProcessState_EAP_DOWN_STAIR MP_EAP_DOWN_STAIR
#define MP_EngineerAutoProcessState_EAP_ENERGY_UNIT MP_EAP_ENERGY_UNIT
#define MP_EngineerAutoProcessState_EAP_EXCHANGE_ORE MP_EAP_EXCHANGE_ORE
#define MP_EngineerAutoProcessState_EAP_STORE_ORE MP_EAP_STORE_ORE
#define MP_EngineerAutoProcessState_EAP_GROUND_ORE MP_EAP_GROUND_ORE

#define _MP_EngineerControlMode_MIN MP_ECM_NONE
#define _MP_EngineerControlMode_MAX MP_ECM_CONTROLLER
#define _MP_EngineerControlMode_ARRAYSIZE ((MP_EngineerControlMode)(MP_ECM_CONTROLLER+1))
#define MP_EngineerControlMode_ECM_NONE MP_ECM_NONE
#define MP_EngineerControlMode_ECM_RC MP_ECM_RC
#define MP_EngineerControlMode_ECM_KEYBOARD MP_ECM_KEYBOARD
#define MP_EngineerControlMode_ECM_CONTROLLER MP_ECM_CONTROLLER



#define MP_EngineerDataPacketToClient_current_process_ENUMTYPE MP_EngineerAutoProcessState
#define MP_EngineerDataPacketToClient_ctrl_mode_ENUMTYPE MP_EngineerControlMode


/* Initializer values for message structs */
#define MP_ArmState_init_default                 {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define MP_EngineerStatus_init_default           {0, 0, 0}
#define MP_EngineerDataPacketToClient_init_default {false, _MP_EngineerAutoProcessState_MIN, false, _MP_EngineerControlMode_MIN, false, MP_ChassisState_init_default, false, MP_ArmState_init_default, false, MP_WeaponState_init_default, false, MP_VisionData_init_default, false, MP_EngineerStatus_init_default, false, MP_RadioInfo_init_default, false, MP_VTExtrinsic_init_default}
#define MP_ArmState_init_zero                    {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define MP_EngineerStatus_init_zero              {0, 0, 0}
#define MP_EngineerDataPacketToClient_init_zero  {false, _MP_EngineerAutoProcessState_MIN, false, _MP_EngineerControlMode_MIN, false, MP_ChassisState_init_zero, false, MP_ArmState_init_zero, false, MP_WeaponState_init_zero, false, MP_VisionData_init_zero, false, MP_EngineerStatus_init_zero, false, MP_RadioInfo_init_zero, false, MP_VTExtrinsic_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define MP_ArmState_angle_yaw_tag                1
#define MP_ArmState_angle_pitch1_tag             2
#define MP_ArmState_angle_pitch2_tag             3
#define MP_ArmState_angle_pitch3_tag             4
#define MP_ArmState_angle_roll_tag               5
#define MP_ArmState_angle_end_pitch_tag          6
#define MP_ArmState_angle_end_roll_tag           7
#define MP_ArmState_length_grip_tag              8
#define MP_ArmState_grip_close_tag               9
#define MP_EngineerStatus_p3_lock_tag            1
#define MP_EngineerStatus_robot_init_ok_tag      2
#define MP_EngineerStatus_controlled_by_controller_tag 3
#define MP_EngineerDataPacketToClient_current_process_tag 1
#define MP_EngineerDataPacketToClient_ctrl_mode_tag 2
#define MP_EngineerDataPacketToClient_chassis_tag 3
#define MP_EngineerDataPacketToClient_arm_tag    4
#define MP_EngineerDataPacketToClient_weapon_tag 5
#define MP_EngineerDataPacketToClient_vision_tag 6
#define MP_EngineerDataPacketToClient_status_tag 7
#define MP_EngineerDataPacketToClient_radio_info_tag 8
#define MP_EngineerDataPacketToClient_vt_extrinsic_tag 9

/* Struct field encoding specification for nanopb */
#define MP_ArmState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_yaw,         1) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_pitch1,      2) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_pitch2,      3) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_pitch3,      4) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_roll,        5) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_end_pitch,   6) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_end_roll,    7) \
X(a, STATIC,   SINGULAR, FLOAT,    length_grip,       8) \
X(a, STATIC,   SINGULAR, BOOL,     grip_close,        9)
#define MP_ArmState_CALLBACK NULL
#define MP_ArmState_DEFAULT NULL

#define MP_EngineerStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     p3_lock,           1) \
X(a, STATIC,   SINGULAR, BOOL,     robot_init_ok,     2) \
X(a, STATIC,   SINGULAR, BOOL,     controlled_by_controller,   3)
#define MP_EngineerStatus_CALLBACK NULL
#define MP_EngineerStatus_DEFAULT NULL

#define MP_EngineerDataPacketToClient_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    current_process,   1) \
X(a, STATIC,   OPTIONAL, UENUM,    ctrl_mode,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  chassis,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  arm,               4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  weapon,            5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  vision,            6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  radio_info,        8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  vt_extrinsic,      9)
#define MP_EngineerDataPacketToClient_CALLBACK NULL
#define MP_EngineerDataPacketToClient_DEFAULT NULL
#define MP_EngineerDataPacketToClient_chassis_MSGTYPE MP_ChassisState
#define MP_EngineerDataPacketToClient_arm_MSGTYPE MP_ArmState
#define MP_EngineerDataPacketToClient_weapon_MSGTYPE MP_WeaponState
#define MP_EngineerDataPacketToClient_vision_MSGTYPE MP_VisionData
#define MP_EngineerDataPacketToClient_status_MSGTYPE MP_EngineerStatus
#define MP_EngineerDataPacketToClient_radio_info_MSGTYPE MP_RadioInfo
#define MP_EngineerDataPacketToClient_vt_extrinsic_MSGTYPE MP_VTExtrinsic

extern const pb_msgdesc_t MP_ArmState_msg;
extern const pb_msgdesc_t MP_EngineerStatus_msg;
extern const pb_msgdesc_t MP_EngineerDataPacketToClient_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MP_ArmState_fields &MP_ArmState_msg
#define MP_EngineerStatus_fields &MP_EngineerStatus_msg
#define MP_EngineerDataPacketToClient_fields &MP_EngineerDataPacketToClient_msg

/* Maximum encoded size of messages (where known) */
#define MASTERPILOT_PROTO_MASTERPILOT_PROTO_ENGINEER_PB_H_MAX_SIZE MP_EngineerDataPacketToClient_size
#define MP_ArmState_size                         42
#define MP_EngineerDataPacketToClient_size       654
#define MP_EngineerStatus_size                   6

/* Mapping from canonical names (mangle_names or overridden package name) */
#define masterpilot_proto_EngineerAutoProcessState MP_EngineerAutoProcessState
#define masterpilot_proto_EngineerControlMode MP_EngineerControlMode
#define masterpilot_proto_ArmState MP_ArmState
#define masterpilot_proto_EngineerStatus MP_EngineerStatus
#define masterpilot_proto_EngineerDataPacketToClient MP_EngineerDataPacketToClient
#define _masterpilot_proto_EngineerAutoProcessState_MIN _MP_EngineerAutoProcessState_MIN
#define _masterpilot_proto_EngineerAutoProcessState_MAX _MP_EngineerAutoProcessState_MAX
#define _masterpilot_proto_EngineerAutoProcessState_ARRAYSIZE _MP_EngineerAutoProcessState_ARRAYSIZE
#define _masterpilot_proto_EngineerControlMode_MIN _MP_EngineerControlMode_MIN
#define _masterpilot_proto_EngineerControlMode_MAX _MP_EngineerControlMode_MAX
#define _masterpilot_proto_EngineerControlMode_ARRAYSIZE _MP_EngineerControlMode_ARRAYSIZE
#define masterpilot_proto_ArmState_init_default MP_ArmState_init_default
#define masterpilot_proto_EngineerStatus_init_default MP_EngineerStatus_init_default
#define masterpilot_proto_EngineerDataPacketToClient_init_default MP_EngineerDataPacketToClient_init_default
#define masterpilot_proto_ArmState_init_zero MP_ArmState_init_zero
#define masterpilot_proto_EngineerStatus_init_zero MP_EngineerStatus_init_zero
#define masterpilot_proto_EngineerDataPacketToClient_init_zero MP_EngineerDataPacketToClient_init_zero

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
