/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MASTERPILOT_PROTO_MASTERPILOT_PROTO_HERO_PB_H_INCLUDED
#define PB_MASTERPILOT_PROTO_MASTERPILOT_PROTO_HERO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* 英雄发送给自定义客户端的数据 */
typedef struct _MP_HeroDataPacketToClient {
    /* 压缩后的相机画面 */
    pb_callback_t camera_frame;
} MP_HeroDataPacketToClient;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define MP_HeroDataPacketToClient_init_default   {{{NULL}, NULL}}
#define MP_HeroDataPacketToClient_init_zero      {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define MP_HeroDataPacketToClient_camera_frame_tag 200

/* Struct field encoding specification for nanopb */
#define MP_HeroDataPacketToClient_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, BYTES,    camera_frame,    200)
#define MP_HeroDataPacketToClient_CALLBACK pb_default_field_callback
#define MP_HeroDataPacketToClient_DEFAULT NULL

extern const pb_msgdesc_t MP_HeroDataPacketToClient_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MP_HeroDataPacketToClient_fields &MP_HeroDataPacketToClient_msg

/* Maximum encoded size of messages (where known) */
/* MP_HeroDataPacketToClient_size depends on runtime parameters */

/* Mapping from canonical names (mangle_names or overridden package name) */
#define masterpilot_proto_HeroDataPacketToClient MP_HeroDataPacketToClient
#define masterpilot_proto_HeroDataPacketToClient_init_default MP_HeroDataPacketToClient_init_default
#define masterpilot_proto_HeroDataPacketToClient_init_zero MP_HeroDataPacketToClient_init_zero

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
