/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MASTERPILOT_PROTO_MASTERPILOT_PROTO_INFANTRY_PB_H_INCLUDED
#define PB_MASTERPILOT_PROTO_MASTERPILOT_PROTO_INFANTRY_PB_H_INCLUDED
#include <pb.h>
#include "masterpilot/proto/common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _MP_InfantryDataPacketToClient {
    bool has_weapon;
    MP_WeaponState weapon;
    bool has_chassis;
    MP_ChassisState chassis;
    bool has_vision;
    MP_VisionData vision;
    bool has_leg_state;
    MP_LegInfo leg_state;
    bool has_radio_info;
    MP_RadioInfo radio_info;
    bool has_vt_extrinsic;
    MP_VTExtrinsic vt_extrinsic;
} MP_InfantryDataPacketToClient;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define MP_InfantryDataPacketToClient_init_default {false, MP_WeaponState_init_default, false, MP_ChassisState_init_default, false, MP_VisionData_init_default, false, MP_LegInfo_init_default, false, MP_RadioInfo_init_default, false, MP_VTExtrinsic_init_default}
#define MP_InfantryDataPacketToClient_init_zero  {false, MP_WeaponState_init_zero, false, MP_ChassisState_init_zero, false, MP_VisionData_init_zero, false, MP_LegInfo_init_zero, false, MP_RadioInfo_init_zero, false, MP_VTExtrinsic_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define MP_InfantryDataPacketToClient_weapon_tag 1
#define MP_InfantryDataPacketToClient_chassis_tag 2
#define MP_InfantryDataPacketToClient_vision_tag 3
#define MP_InfantryDataPacketToClient_leg_state_tag 5
#define MP_InfantryDataPacketToClient_radio_info_tag 8
#define MP_InfantryDataPacketToClient_vt_extrinsic_tag 9

/* Struct field encoding specification for nanopb */
#define MP_InfantryDataPacketToClient_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  weapon,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  chassis,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  vision,            3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  leg_state,         5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  radio_info,        8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  vt_extrinsic,      9)
#define MP_InfantryDataPacketToClient_CALLBACK NULL
#define MP_InfantryDataPacketToClient_DEFAULT NULL
#define MP_InfantryDataPacketToClient_weapon_MSGTYPE MP_WeaponState
#define MP_InfantryDataPacketToClient_chassis_MSGTYPE MP_ChassisState
#define MP_InfantryDataPacketToClient_vision_MSGTYPE MP_VisionData
#define MP_InfantryDataPacketToClient_leg_state_MSGTYPE MP_LegInfo
#define MP_InfantryDataPacketToClient_radio_info_MSGTYPE MP_RadioInfo
#define MP_InfantryDataPacketToClient_vt_extrinsic_MSGTYPE MP_VTExtrinsic

extern const pb_msgdesc_t MP_InfantryDataPacketToClient_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MP_InfantryDataPacketToClient_fields &MP_InfantryDataPacketToClient_msg

/* Maximum encoded size of messages (where known) */
#define MASTERPILOT_PROTO_MASTERPILOT_PROTO_INFANTRY_PB_H_MAX_SIZE MP_InfantryDataPacketToClient_size
#define MP_InfantryDataPacketToClient_size       624

/* Mapping from canonical names (mangle_names or overridden package name) */
#define masterpilot_proto_InfantryDataPacketToClient MP_InfantryDataPacketToClient
#define masterpilot_proto_InfantryDataPacketToClient_init_default MP_InfantryDataPacketToClient_init_default
#define masterpilot_proto_InfantryDataPacketToClient_init_zero MP_InfantryDataPacketToClient_init_zero

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
